FROM ubuntu:18.04

USER root
WORKDIR /opt

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV M2_HOME=/opt/apache-maven-3.8.1
ENV MAVEN_HOME=/opt/apache-maven-3.8.1
ENV PATH=${JAVA_HOME}/bin:${M2_HOME}/bin:${PATH}

RUN apt-get update \
    && apt-get -y install wget openjdk-11-jdk \
    && wget https://archive.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz \
    && tar -xvzf apache-maven-3.8.1-bin.tar.gz
