micronaut:

  application:
    name: micronautSecurityOauth2
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: 'http://localhost:9000/auth/realms/master/protocol/openid-connect/certs'
      roles-name: scope
      roles-separator: ' '
netty:
  default:
    allocator:
      max-order: 3
