FROM base-jvm-image:v1

COPY quarkus-rabbitmq-producer /opt/quarkus-rabbitmq-producer
WORKDIR /opt/quarkus-rabbitmq-producer
RUN mvn package -Dquarkus.package.type=uber-jar
CMD ["java", "-jar", "./target/quarkus-rabbitmq-producer-1.0.0-SNAPSHOT-runner.jar"]
