
FROM base-jvm-image:v1

COPY springboot-rabbitmq-producer /opt/springboot-rabbitmq-producer
WORKDIR /opt/springboot-rabbitmq-producer
RUN mvn package -DskipTests=true
CMD ["java", "-jar", "./target/springboot-rabbitmq-producer-0.0.1-SNAPSHOT.jar"]
