FROM base-jvm-image:v1

COPY hello-world /opt/hello-world
WORKDIR /opt/hello-world
RUN mvn package -Dquarkus.package.type=uber-jar -DskipTests
CMD ["java", "-jar", "./target/hello-world-1.0.0-SNAPSHOT-runner.jar"]
